version: 1
update_configs:
  - package_manager: python
    directory: ./
    update_schedule: daily
    allowed_updates:
      - match:
          dependency_name: "pip"
      - match:
          dependency_name: "click"
